sul-dlss/dataworks-etl

Gemfile
Gemfile.lock
app/services/dataworks_mappers/base.rb
app/services/dataworks_mappers/mapping_error.rb
app/services/dataworks_mappers/redivis.rb
app/services/dataworks_validator.rb
config/dataworks_schema.yml
spec/services/dataworks_mappers/base_spec.rb
spec/services/dataworks_validator_spec.rb

Adds validation of dataworks metadata.

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Add simplecov, does not configure it within CI or checks.

Add simplecov and produce coverage report after tests

---

config/dataworks_schema.yml
spec/services/dataworks_validator_spec.rb

Adds additional fields to Dataworks schema.

---

app/jobs/zenodo_etl_job.rb
app/services/dataworks_mappers/zenodo.rb
config/dataworks_schema.yml
config/recurring.yml
spec/fixtures/sources/zenodo.json
spec/jobs/zenodo_etl_job_spec.rb
spec/services/dataworks_mappers/zenodo_spec.rb

Adds Zenodo mapper.

---

Gemfile
Gemfile.lock
app/services/clients/dryad.rb
app/services/extractors/client_base.rb
app/services/extractors/dryad.rb
config/settings.yml
config/settings/test.yml
spec/services/extractors/dryad_spec.rb

Adds extractor for Dryad.

---

.rubocop.yml
app/services/dataworks_mappers/dryad.rb
app/services/dataworks_mappers/zenodo.rb
spec/fixtures/sources/dryad.json
spec/services/dataworks_mappers/dryad_spec.rb

Fixes #9 
I have extracted the dryad records locally and run this mapping against them without error.

Implement Dryad metadata mapping

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

Adds honeybadger.

---

config/initializers/config.rb

Set config to use env variables.

---

README.md
app/services/extractors/base.rb
app/services/extractors/datacite.rb
app/services/extractors/dryad.rb
app/services/extractors/zenodo.rb
config/datasets/datacite.yml
config/datasets/dryad.yml
config/datasets/zenodo.yml
spec/services/extractors/datacite_spec.rb
spec/services/extractors/dryad_spec.rb
spec/services/extractors/zenodo_spec.rb

Supports extracting extra datasets for datacite.

---

app/services/clients/solr.rb
app/services/extractors/searchworks.rb
spec/services/extractors/searchworks_spec.rb

Supports extracting extra datasets for Searchworks.

---

Gemfile
Gemfile.lock
config/initializers/okcomputer.rb

Adds OK computer.

---

.github/workflows/ci.yml

Fixes #3 
Adds the test run and coverage report to the github action.

Setup github action for tests and coverage

---

README.md
app/jobs/local_etl_job.rb
app/services/clients/base.rb
app/services/clients/list_result.rb
app/services/dataworks_mappers/local.rb
app/services/dataworks_validator.rb
app/services/extractors/local.rb
app/services/transformer_loader.rb
config/dataworks_schema.yml
config/local_datasets/example.yml
config/recurring.yml
config/settings.yml
spec/fixtures/local_datasets/example.yml
spec/jobs/local_etl_job_spec.rb
spec/services/dataworks_mappers/local_spec.rb
spec/services/extractors/local_spec.rb

Adds ETL for local files.

---

Jenkinsfile

Fixes #7 
Depends on: https://github.com/sul-dlss/puppet/pull/12243

Adds the Jenkinsfile for continuous deployment

---

app/jobs/dryad_etl_job.rb
config/recurring.yml
config/settings.yml
spec/jobs/dryad_etl_job_spec.rb

Adds Dryad ETL job.

---

config/recurring.yml
config/settings.yml

Configure ETL jobs for SUL and SDSS.

---

app/services/solr_mapper.rb
spec/services/solr_mapper_spec.rb

What this pull request does:
Adds creator names, ids, funder names, ids, and url to the index.

adding creator, funder, and url information to Solr

---

app/services/transformer_loader.rb

Adds HB context for transform and load.

---

app/services/solr_mapper.rb
config/dataworks_schema.yml
spec/services/dataworks_validator_spec.rb
spec/services/solr_mapper_spec.rb

Make creators optional.

---

app/services/solr_mapper.rb
spec/services/solr_mapper_spec.rb

Map contributor fields to solr doc.

---

app/services/solr_mapper.rb
spec/services/solr_mapper_spec.rb

Maps additional struct fields to solr doc.

---

app/services/solr_mapper.rb
spec/services/solr_mapper_spec.rb

Map related identifiers to solr doc.

---

app/services/dataworks_mappers/base.rb
app/services/transformer_loader.rb
spec/services/transformer_loader_spec.rb

Adds support for fail fast on mapping.

---

app/services/dataworks_mappers/redivis.rb
spec/services/dataworks_mappers/redivis_spec.rb

Fix access mapping for Redivis.

---

app/services/transformer_loader.rb
config/settings.yml
spec/services/transformer_loader_spec.rb

Support ignoring datasets with mapping errors.

---

app/services/extractors/base.rb
app/services/extractors/datacite.rb
app/services/solr_service.rb
app/services/transformer_loader.rb
db/migrate/20250425162621_add_etl_key_to_dataset_record_set.rb
db/schema.rb
spec/factories/dataset_record_sets.rb
spec/services/extractors/datacite_spec.rb
spec/services/solr_service_spec.rb
spec/services/transformer_loader_spec.rb

Delete outdated record sets.

---

app/services/clients/redivis.rb
app/services/extractors/redivis.rb
spec/services/clients/redivis_spec.rb
spec/services/extractors/redivis_spec.rb

For redivis client, move organization to list param.

---

app/services/dataworks_mappers/redivis.rb
spec/services/dataworks_mappers/redivis_spec.rb

Use variable label for redivis mapping.

---

app/services/solr_mapper.rb
app/services/solr_mappers/titles.rb
spec/services/solr_mapper_spec.rb

Adds version to primary title.

---

Gemfile
Gemfile.lock
app/services/date_parsing.rb
app/services/solr_mapper.rb
spec/services/date_parsing_spec.rb

This switches from ParseDate to Edtf for ambiguous date parsing and returning a range array.
Fixes #159 
Fixes #163

Extract date parsing service

---

app/services/clients/datacite.rb
app/services/extractors/datacite.rb
config/recurring.yml
config/settings.yml
spec/services/clients/datacite_spec.rb
spec/services/extractors/datacite_spec.rb

Adds datacite sul provider extraction.

---

app/services/solr_mapper.rb
spec/services/solr_mapper_spec.rb

updating Solr id to be Blacklight friendly

---

app/services/dataworks_mappers/base.rb
app/services/dataworks_mappers/sdr.rb
app/services/extractors/base.rb
config/dataworks_schema.yml
spec/fixtures/sources/sdr.json
spec/services/dataworks_mappers/sdr_spec.rb

- Map Cocina data from SDR to our schema
- Add RelatedItem support to the schema
closes #11

Map cocina data from SDR

---

app/jobs/sdr_extract_job.rb
config/recurring.yml
config/settings.yml
spec/jobs/sdr_extract_job_spec.rb

HB checkin PR: https://github.com/sul-dlss/shared_configs/pull/2338

Add an SDR extraction job

---

app/jobs/datacite_extract_job.rb

Datacite extract job needs the option of also passing in provider id

adding provider id to extract job options

---

app/services/extractors/base.rb
spec/services/extractors/datacite_spec.rb
spec/services/extractors/dryad_spec.rb
spec/services/extractors/redivis_spec.rb
spec/services/extractors/zenodo_spec.rb

Use modified token when finding existing DatasetRecords in extraction.

---

config/settings.yml

This set of datasets is failing for various reasons (as specified in the comments). In order to allow indexing to proceed for the rest of the datasets, we need to add these to our list of datasets to ignore currently.

adding datasets to ignore list

---

app/services/dataworks_mappers/sdr.rb
spec/services/dataworks_mappers/sdr_spec.rb

Allow Sdr mapper to accept hash.

---

app/services/solr_mapper.rb
config/settings.yml
config/settings/test.yml
spec/services/solr_mapper_spec.rb

Adds courses to index.

---

app/services/dataset_transformer_loader.rb
app/services/solr_mapper.rb
spec/services/dataset_transformer_loader_spec.rb
spec/services/solr_mapper_spec.rb

Adds provider ids to solr doc.

---

app/services/dataset_transformer_loader.rb
app/services/transformer_loader.rb
spec/factories/dataset_records.rb
spec/services/dataset_transformer_loader_spec.rb

Support merging fields from other dataset records.

---

app/services/dataset_transformer_loader.rb

Remove ignored datasets when performing a transform and load.

---

app/services/clients/open_alex.rb
app/services/extractors/open_alex.rb
config/datasets/open_alex.yml
spec/services/clients/open_alex_spec.rb
spec/services/extractors/open_alex_spec.rb

Adds OpenAlex extractor.

---

app/services/dataworks_mappers/open_alex.rb
config/dataworks_schema.yml
config/settings.yml
spec/fixtures/sources/open_alex.json
spec/services/dataworks_mappers/open_alex_spec.rb

Add OpenAlex mapping with test and fixture object

---

config/local_datasets/data2nhgis.yml
config/local_datasets/democratizing_chicagos_menu_money.yml
config/local_datasets/first_person_narratives_of_the_american_south.yml
config/local_datasets/global_surface_water.yml
config/local_datasets/mapping_inequality.yml
config/local_datasets/tweets_of_congress.yml
config/settings.yml

adding teaching datastes, adding creators, associating with courses

---

app/services/clients/open_alex.rb
app/services/extractors/open_alex.rb
config/settings.yml
spec/cassettes/Clients_OpenAlex/when_API_token_is_provided/includes_the_API_token_in_the_request.yml
spec/services/clients/open_alex_spec.rb

Send an API key to OpenAlex if configured

---

app/services/dataset_transformer.rb
app/services/metadata_cleaner.rb
spec/fixtures/solr_documents/test.json
spec/services/metadata_cleaner_spec.rb

Updating indexing and cleanup of strings
